-- ----------------------------------------------------------------
--          Indyco Builder - Auto-Generated DDL Script           --
-- ----------------------------------------------------------------
--
-- Project Name . . . . . . : estesiquesi
--  + Exported Datamarts. . : Datamart
--  + Export Timestamp. . . : 2019-10-24 19:20:07
--
-- Selected Profile . . . . : Star Schema
--  + Shared Hierarchies. . : Snowflake
--  + Cross Dimensional Attr: Bridge table without surrogates
--  + Degenerate Dimensions : Use fact table
--  + Multiple Arcs . . . . : Bridge table without surrogates
--  + Recursions. . . . . . : Use self-referencing keys
--
-- Target DB. . . . . . . . : Oracle Database
--  + Export Primary Keys . : True
--  + Export Foreign Keys . : True
--  + Nullable columns. . . : True
--
-- ----------------------------------------------------------------

CREATE TABLE "DT_TIME"
(
  "ID_TIME" NUMBER (9),
  "TIME" VARCHAR2 (255 CHAR),
  "ID" VARCHAR2 (255 CHAR),
  "ID_ID" NUMBER (9),
  "DAY" VARCHAR2 (255 CHAR),
  "ID_DAY" NUMBER (9),
  "MONTH" VARCHAR2 (255 CHAR),
  "ID_MONTH" NUMBER (9),
  "YEAR" VARCHAR2 (255 CHAR),
  "ID_YEAR" NUMBER (9)
);
ALTER TABLE "DT_TIME" ADD CONSTRAINT "PK_DT_TIME" PRIMARY KEY ("ID_TIME");





CREATE TABLE "DT_AIRCRAFT"
(
  "ID_AIRCRAFT" NUMBER (9),
  "AIRCRAFT" VARCHAR2 (255 CHAR),
  "ID" VARCHAR2 (255 CHAR),
  "ID_ID" NUMBER (9),
  "MODEL" VARCHAR2 (255 CHAR),
  "ID_MODEL" NUMBER (9),
  "REGNR" VARCHAR2 (255 CHAR),
  "ID_REGNR" NUMBER (9),
  "MANUFACTURER" VARCHAR2 (255 CHAR),
  "ID_MANUFACTURER" NUMBER (9),
  "MAINTENANCE" VARCHAR2 (255 CHAR),
  "ID_MAINTENANCE" NUMBER (9)
);
ALTER TABLE "DT_AIRCRAFT" ADD CONSTRAINT "PK_DT_AIRCRAFT" PRIMARY KEY ("ID_AIRCRAFT");





CREATE TABLE "FT_METRICS"
(
  "ID_MAINTENANCEREPORT" NUMBER (9),
  "ID_FLIGHTINFO" NUMBER (9),
  "ID_TIME" NUMBER (9),
  "ID_AIRCRAFT" NUMBER (9),
  "ID" NUMBER (18,3),
  "TIMEID" NUMBER (18,3),
  "MAINTENANCEREPORTID" NUMBER (18,3),
  "FLIGHTINFOID" NUMBER (18,3),
  "AIRCRAFTID" NUMBER (18,3)
);
ALTER TABLE "FT_METRICS" ADD CONSTRAINT "PK_FT_METRICS" PRIMARY KEY ("ID_MAINTENANCEREPORT", "ID_FLIGHTINFO", "ID_TIME", "ID_AIRCRAFT");





CREATE TABLE "DT_MAINTENANCEREPORT"
(
  "ID_MAINTENANCEREPORT" NUMBER (9),
  "MAINTENANCEREPORT" VARCHAR2 (255 CHAR),
  "ID" VARCHAR2 (255 CHAR),
  "AIRPORTNAME" VARCHAR2 (255 CHAR),
  "OTHER" VARCHAR2 (255 CHAR)
);
ALTER TABLE "DT_MAINTENANCEREPORT" ADD CONSTRAINT "PK_DT_MAINTENANCEREPORT" PRIMARY KEY ("ID_MAINTENANCEREPORT");





CREATE TABLE "DT_FLIGHTINFO"
(
  "ID_FLIGHTINFO" NUMBER (9),
  "FLIGHTINFO" VARCHAR2 (255 CHAR),
  "ID" VARCHAR2 (255 CHAR),
  "FLIGHTNR" VARCHAR2 (255 CHAR),
  "AIRCRAFTREGNR" VARCHAR2 (255 CHAR),
  "ORIGIN" VARCHAR2 (255 CHAR),
  "DESTINATION" VARCHAR2 (255 CHAR),
  "STATUS" VARCHAR2 (255 CHAR),
  "LOGBOOK" VARCHAR2 (255 CHAR)
);
ALTER TABLE "DT_FLIGHTINFO" ADD CONSTRAINT "PK_DT_FLIGHTINFO" PRIMARY KEY ("ID_FLIGHTINFO");





CREATE TABLE "FT_SERVICETIME"
(
  "ID_AIRCRAFT" NUMBER (9),
  "ID_TIME" NUMBER (9),
  "ID" NUMBER (18,3),
  "TIMEID" NUMBER (18,3),
  "AIRCRAFTID" NUMBER (18,3)
);
ALTER TABLE "FT_SERVICETIME" ADD CONSTRAINT "PK_FT_SERVICETIME" PRIMARY KEY ("ID_AIRCRAFT", "ID_TIME");








ALTER TABLE "FT_METRICS" ADD CONSTRAINT "FK_FT_METRICS_ID_MNTN_ID_MNTN" FOREIGN KEY ("ID_MAINTENANCEREPORT") REFERENCES "DT_MAINTENANCEREPORT" ("ID_MAINTENANCEREPORT");
ALTER TABLE "FT_METRICS" ADD CONSTRAINT "FK_FT_METRICS_ID_FLGH_ID_FLGH" FOREIGN KEY ("ID_FLIGHTINFO") REFERENCES "DT_FLIGHTINFO" ("ID_FLIGHTINFO");
ALTER TABLE "FT_METRICS" ADD CONSTRAINT "FK_FT_METRICS_ID_TIME_ID_TIME" FOREIGN KEY ("ID_TIME") REFERENCES "DT_TIME" ("ID_TIME");
ALTER TABLE "FT_METRICS" ADD CONSTRAINT "FK_FT_METRICS_ID_ARCR_ID_ARCR" FOREIGN KEY ("ID_AIRCRAFT") REFERENCES "DT_AIRCRAFT" ("ID_AIRCRAFT");



ALTER TABLE "FT_SERVICETIME" ADD CONSTRAINT "FK_FT_SRVC_ID_ARCR_ID_ARCR" FOREIGN KEY ("ID_AIRCRAFT") REFERENCES "DT_AIRCRAFT" ("ID_AIRCRAFT");
ALTER TABLE "FT_SERVICETIME" ADD CONSTRAINT "FK_FT_SRVC_ID_TIME_ID_TIME" FOREIGN KEY ("ID_TIME") REFERENCES "DT_TIME" ("ID_TIME");


-- DROP TABLE "DT_TIME" CASCADE CONSTRAINTS;
-- DROP TABLE "DT_AIRCRAFT" CASCADE CONSTRAINTS;
-- DROP TABLE "FT_METRICS" CASCADE CONSTRAINTS;
-- DROP TABLE "DT_MAINTENANCEREPORT" CASCADE CONSTRAINTS;
-- DROP TABLE "DT_FLIGHTINFO" CASCADE CONSTRAINTS;
-- DROP TABLE "FT_SERVICETIME" CASCADE CONSTRAINTS;


--view creation 


CREATE MATERIALIZED VIEW AircraftUtilization
BUILD immediate
ON demand
AS SELECT a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR, 
    SUM(st.USABLE)/24 as ADIS,
    SUM(st.MAINTENANCEDURATION)/24 as ADOS
  FROM DT_AIRCRAFT a, DT_TIME t, FT_SERVICETIME st
  WHERE st.PK_FT_SERVICETIME=t.ID_TIME
    AND st.PK_FT_SERVICETIME=a.ID_AIRCRAFT
  GROUP BY a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR
  ORDER BY a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR


CREATE MATERIALIZED VIEW Reporting
BUILD immediate
ON demand 
AS SELECT a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR,
    SUM(m.AIRTIME) as FH,
    SUM(m.DEPARTURES) as TOs,
    (SUM(m.LOGBOOK)/SUM(m.AIRTIME))*1000 as RRH,
    (SUM(m.LOGBOOK)/SUM(m.DEPARTURES)*100 as RRC,
  FROM DT_AIRCRAFT a, DT_TIME t, DT_FLIGHTINFO fI, FT_METRICS
  WHERE m.PK_FT_METRICS=a.ID_AIRCRAFT
    AND  m.PK_FT_METRICS=t.ID_TIME
    AND  m.PK_FT_METRICS=fi.ID_FLIGHTINFO

  GROUP BY a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR
  ORDER BY a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR


CREATE MATERIALIZED VIEW Rates
BUILD immediate
ON demand 
AS SELECT a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR,
    SUM(m.AIRTIME) as FH,
    SUM(m.DEPARTURES) as TOs
    SUM(CASE WHEN fi.STATUS = 'CANCELLED' THEN 1 ELSE 0 END)/COUNT(TO)) *100 as CNR,
    SUM(CASE WHEN fi.STATUS = 'DELAYED' THEN 1 ELSE 0 END)/COUNT(TO) ) *100 as DYR,
  FROM DT_AIRCRAFT a, DT_TIME t, DT_FLIGHTINFO fi, FT_METRICS M
  WHERE m.PK_FT_METRICS=a.ID_AIRCRAFT
    AND  m.PK_FT_METRICS=t.ID_TIME
    AND  m.PK_FT_METRICS=fi.ID_FLIGHTINFO
    AND FI.AIRCRAFTREGNR = a.AIRCRAFTREGNR
  GROUP BY a.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR
    HAVING COUNT(TO) = 100
  ORDER BYa.ID_AIRCRAFT, a.MODEL, a.MANUFACTURER, t.DAY, t.MONTH, t.YEAR;




